kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devspaces-user-container-build
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - container-build
