kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-devspaces-cheworkspaces-devworkspace-clusterrole
  namespace: awsdeveloper-devspaces
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: awsdeveloper
    namespace: awsdeveloper-devspaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-devspaces-cheworkspaces-devworkspace-clusterrole
