kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devspaces-user-container-build
  namespace: awsdeveloper-devspaces
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: awsdeveloper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devspaces-user-container-build
