kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-devspaces-cheworkspaces-devworkspace-clusterrole
rules:
  - verbs:
      - get
      - create
      - delete
      - list
      - update
      - patch
      - watch
    apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspaces
      - devworkspacetemplates
