kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-gitea-view
  namespace: infra-gitea-operator
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: awsdeveloper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
