kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-operators-deny-delete
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: awsdeveloper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infra-operators-deny-delete-role
