kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-argocd-application-user-binding
  namespace: openshift-gitops
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: awsdeveloper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-argocd-application-user
