apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,CreateNamespace=true
  name: gitea-operator
  namespace: infra-gitea-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitea-operator
  source: redhat-rhpds-gitea
  sourceNamespace: infra-gitea-operator
