---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    security.openshift.io/scc.podSecurityLabelSync: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ai-operator-on-aws