apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openshift-gitops
  - openshift-devspaces
  - rbac
  - kafka-broker
  - kafka-ui
  - logging
  - openshift-virtualization
  - openshift-ai
  - mtv
  - tekton
