apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-admin-coffeeshop-role
rules:
  - apiGroups:
      - "tekton.dev"
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
      - "pipelines.kubeflow.org"
    resources: ["*"]
    verbs: ["*"]
