# https://docs.openshift.com/container-platform/4.10/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html#gitops-additional-permissions-for-cluster-config_configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-devspaces-role
  annotations:
    argocd.argoproj.io/sync-wave: "10"
rules:
  - apiGroups: ["org.eclipse.che"]
    resources: ["*"]
    verbs: ["*"]
