apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - cluster-role-devspaces.yaml
  - cluster-role-gitea.yaml
  - cluster-rolebinding.yaml
