---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aivegoteyes-deploy

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "15"

resources:
  - secret.yaml
  - kafka-broker.yaml
