---
apiVersion: v1
kind: Secret
metadata:
  name: object-detection-kafka
  labels:
    app: object-detection
    app.kubernetes.io/component: object-detection
    app.kubernetes.io/instance: object-detection
    app.kubernetes.io/part-of: object-detection
stringData:
  KAFKA_BOOTSTRAP_SERVER: object-detection-kafka-bootstrap.aivegoteyes-deploy.svc.cluster.local:9092
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  KAFKA_SASL_MECHANISM: PLAIN
  KAFKA_TOPIC_IMAGES: images
  KAFKA_TOPIC_OBJECTS: objects
