apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-ui
  labels:
    strimzi.io/cluster: object-detection
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: cluster
          name: kafka-cluster
          patternType: literal
        operation: IdempotentWrite
        host: "*"
      - resource:
          type: cluster
          name: kafka-cluster
          patternType: literal
        operation: Create
        host: "*"
