apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-ui

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "16"

resources:
  # - kafka-user-1.yml
  # - kafka-user-2.yml
  - deployment.yml
  - service.yml
  - route.yml
