apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-cnv

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "10"

resources:
  - operator-group.yaml
  - subscription.yaml
