---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datascience-cluster-role
rules:
- apiGroups:
  - datasciencecluster.opendatahub.io
  resources:
  - datascienceclusters
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

