apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-gitea-repositories

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - gitea.yaml
  - configmap.yaml
  - job.yaml
