apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtv-operator
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,CreateNamespace=true
spec:
  channel: release-v2.8
  installPlanApproval: Automatic
  name: mtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
